name: water_quality
description: Water Quality App for Google Solution Challenge

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1
  auto_route: ^5.0.4
  intl: ^0.17.0
  loader_overlay: ^2.1.0
  flutter_spinkit: ^5.1.0
  sizer: ^2.0.15
  expandable: ^5.0.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  http: ^0.13.5
  shared_preferences: ^2.0.20
  syncfusion_flutter_charts: ^21.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700